import localFont from "next/font/local";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import Sidebar from "./Sidebar";
import { AuthProvider } from "./AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            {/* Sidebar */}
            <Sidebar />

            {/* Main Content Area */}
            <div className="flex-grow flex flex-col">
              {/* Header */}
              <Header />

              {/* Main Content */}
              <main className="flex-grow pt-16  pl-0 md:pl-64">{children}</main>

              {/* Footer */}
              <Footer />
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
